
so ~/.vim/general.vim
if filereadable(expand('~/.vim/bundle/Vundle.vim/autoload/vundle.vim'))
  so ~/.vim/bundles.vim
endif
so ~/.vim/shortcuts.vim
so ~/.vim/extra.vim

" NOTES
" :set ft=ruby to force the syntax coloration

" au WinLeave * set nocursorline nocursorcolumn
" au WinEnter * set cursorline 
" set cursorline 
